REGISTERED_VACCINES = [
    "rabies",
    "rabies booster",
    "rabies vaccination",
    "imrab",
    "dhpp",
    "dhlpp",
    "DHLP-P",
    "dapp",
    "distemper",
    "parvovirus",
    "parvo",
    "adenovirus",
    "hepatitis vaccine",
    "bordetella",
    "kennel cough",
    "leptospirosis",
    "lepto",
    "lyme vaccine",
    "canine influenza",
    "influenza vaccine",
    "feline leukemia",
    "felv",
    "fvrcp",
    "panleukopenia",
    "calicivirus",
    "rhinotracheitis",
]

REGISTERED_MEDICATIONS = [
    "cerenia",
    "maropitant",
    "apoquel",
    "cefopodoxime",
    "cefpodoxime",
    "metacam",
    "meloxicam",
    "metomemax",
    "mometamax",
    "simparica",
    "simparica trio",
    "heartgard",
    "nexgard",
    "bravecto",
    "revolution",
    "revolution plus",
    "advantage",
    "advantix",
    "frontline",
    "interceptor",
    "trifexis",
    "proheart",
    "prednisone",
    "prednisolone",
    "amoxicillin",
    "clavamox",
    "cephalexin",
    "doxycycline",
    "gabapentin",
    "trazodone",
    "carprofen",
    "rimadyl",
    "deramaxx",
    "galliprant",
    "metronidazole",
    "clindamycin",
    "enrofloxacin",
    "baytril",
    "fluconazole",
    "insulin",
    "prozinc",
    "vetoryl",
    "phenobarbital",
    "levetiracetam",
    "keppra",
    "dexdomitor",
    "dexmedetomidine",
    "atipamezole",
    "antisedan",
    "yobine",
]

MEDICATION_FORM_KEYWORDS = [
    "tablet",
    "tablets",
    "capsule",
    "capsules",
    "injection",
    "injectable",
    "suspension",
    "solution",
    "ointment",
    "cream",
    "drops",
    "spray",
    "shampoo",
    "chew",
    "chewable",
    "oral",
    "topical",
    "dose",
    "mg",
    "mcg",
    "ml",
    "cc",
]

SERVICE_KEYWORDS = [
    "exam",
    "examination",
    "wellness",
    "recheck",
    "consultation",
    "radiograph",
    "x-ray",
    "xray",
    "interpretation",
    "test",
    "screening",
    "bloodwork",
    "blood work",
    "lab",
    "laboratory",
    "nail trim",
    "catheter",
    "disposal",
    "sedation",
    "anesthesia",
    "surgery",
    "procedure",
    "hospitalization",
    "digital image",
    "glucose curve",
]


FIELD_LABELS = {
    "client_name": [
        "client name",
        "owner",
        "owner name",
        "customer",
        "bill to",
        "for",
    ],
    "client_id": [
        "client id",
        "account",
        "account number",
        "acct",
    ],
    "patient_id": [
        "patient id",
        "pet id",
    ],
    "patient_name": [
        "patient name",
        "pet",
        "pet name",
        "name",
    ],
    "species": [
        "species",
    ],
    "breed": [
        "breed",
    ],
    "weight": [
        "weight",
        "wt",
    ],
    "birthday": [
        "birthday",
        "birthdate",
        "dob",
    ],
    "sex": [
        "sex",
        "gender",
    ],
    "invoice_number": [
        "invoice",
        "invoice number",
        "invoice no",
        "invoice #",
        "receipt",
        "receipt number",
    ],
    "invoice_date": [
        "invoice date",
        "date",
        "printed",
    ],
}


TOTAL_LABELS = {
    "subtotal": [
        "patient subtotal",
        "subtotal",
        "total charges this invoice",
    ],
    "discount": [
        "discount",
        "military discount",
        "sr / military discount",
        "senior discount",
    ],
    "tax": [
        "sales tax",
        "tax",
    ],
    "total": [
        "invoice total",
        "total this visit",
        "total",
    ],
    "previous_balance": [
        "previous balance",
        "old balance",
        "your old balance",
    ],
    "payment": [
        "less payment",
        "payment received",
        "total payment",
        "payments",
        "visa payment",
        "mastercard payment",
    ],
    "balance_due": [
        "total now due",
        "new balance",
        "your new balance",
        "balance due",
    ],
}